// QuoteAssist v2 — Requirements backlog data.
// Each module groups small, independently testable tasks. A task carries:
//   id, title, desc, ac:[acceptance criteria], pri:'P0'|'P1'|'P2', status:'done'|'partial'|'planned'
// Status reflects what is built in the current prototype.

window.QAReq = {
  meta: {
    product: 'QuoteAssist',
    release: 'v2 — Multi-tenant platform',
    version: '2.0',
    date: '13 June 2026',
    owner: 'Product',
    summary: 'QuoteAssist becomes a multi-tenant, multi-vertical sales-quoting platform. Agencies set discount quotas per seller level and pricing category; any discount above a seller’s self-approve limit routes through a tiered approval chain before it can reach the client. Three personas — Site Administrator, Agency Admin and Sales Person — each operate their own workspace.'
  },

  glossary: [
    ['Platform', 'The QuoteAssist SaaS as a whole, operated by the Site Administrator.'],
    ['Vertical', 'An industry template (e.g. Airline, Product, Medical) that defines deal terminology, money unit and pricing categories.'],
    ['Agency / Tenant', 'A customer organisation on the platform. Configured to exactly one vertical.'],
    ['Seller level', 'Junior / Senior / Lead — the band an Agency assigns a salesperson; drives their discount quota.'],
    ['Pricing category', 'A vertical-defined product/price grouping that quotas are set against.'],
    ['Self-approve limit', 'Max discount % a seller can apply with no approval.'],
    ['Cap', 'Max discount % reachable with approval. Above the cap is blocked.'],
    ['Guardrail', 'Platform-wide hard ceiling per vertical that no tenant quota may exceed.']
  ],

  modules: [
    {
      code: 'PF', name: 'Platform Foundation & Data Model', accent: 230,
      intro: 'The shared multi-tenant, multi-vertical backbone every persona reads and writes through. Persisted client-side for the prototype; maps 1:1 to server entities in production.',
      tasks: [
        { id: 'PF-01', title: 'Vertical catalog', pri: 'P0', status: 'done',
          desc: 'Define the set of industry verticals the platform supports, each with its own terminology and pricing categories.',
          ac: ['6 seed verticals: Airline, Product/Wholesale, Medical, SaaS, Insurance, Automotive.',
               'Each vertical stores: display name, deal noun + plural, money unit, ordered list of pricing categories.',
               'Verticals are referenced by stable id, never by label.'] },
        { id: 'PF-02', title: 'Tenant (agency) entity', pri: 'P0', status: 'done',
          desc: 'Model an agency as a tenant bound to one vertical, with plan, seat usage, status and billing.',
          ac: ['Fields: name, vertical, plan, seatsUsed, status (active|trial|suspended), MRR, owner, region, created.',
               'Each tenant references exactly one vertical id.',
               'Seat limit is derived from the plan.'] },
        { id: 'PF-03', title: 'Seller levels', pri: 'P0', status: 'done',
          desc: 'Three ordered seller levels used as the unit that discount quotas attach to.',
          ac: ['Levels: Junior < Senior < Lead, ordered.', 'Every salesperson holds exactly one level.'] },
        { id: 'PF-04', title: 'Discount quota matrix', pri: 'P0', status: 'done',
          desc: 'Per-tenant matrix of { self, cap } discount percentages indexed by level × pricing category.',
          ac: ['On tenant creation, a default matrix is seeded from the vertical’s categories.',
               'self ≤ cap is enforced at write time (raising self raises cap; lowering cap lowers self).',
               'self and cap are clamped to the vertical guardrail.'] },
        { id: 'PF-05', title: 'Deal entity', pri: 'P1', status: 'done',
          desc: 'A quote/order/deal owned by a seller, carrying value, category and a base discount.',
          ac: ['Fields: ref, customer, category, value, seller, baseDiscount, status.', 'Category is one of the tenant vertical’s categories.'] },
        { id: 'PF-06', title: 'Approval request entity', pri: 'P0', status: 'done',
          desc: 'A record created when a seller asks for a discount above their self-approve limit.',
          ac: ['Fields: tenant, deal, customer, category, value, seller, level, current %, requested %, routedTo, reason, status, timestamps, decidedBy, note.',
               'Status lifecycle: pending → approved | rejected.'] },
        { id: 'PF-07', title: 'Activity log', pri: 'P1', status: 'done',
          desc: 'Append-only feed of request and decision events for audit + the activity panel.',
          ac: ['Every request creation and decision appends an entry.', 'Entries ordered newest-first; carry actor, deal, %, timestamp.'] },
        { id: 'PF-08', title: 'Client persistence', pri: 'P1', status: 'done',
          desc: 'All entities persist across reloads under a namespaced key, with seed fallback.',
          ac: ['Reads fall back to seed data when storage is empty.', 'Writes are namespaced to avoid colliding with other app state.'] },
        { id: 'PF-09', title: 'Server API & RBAC', pri: 'P0', status: 'planned',
          desc: 'Replace client store with authenticated, tenant-scoped REST/GraphQL endpoints.',
          ac: ['All reads/writes scoped to the caller’s tenant (except platform admin).', 'Role-based authorisation on every endpoint.', 'Optimistic concurrency on quota + request writes.'] }
      ]
    },
    {
      code: 'SA', name: 'Site Administrator', accent: 295,
      intro: 'The platform operator. Onboards agencies, defines verticals, sets global guardrails and watches cross-tenant usage.',
      tasks: [
        { id: 'SA-01', title: 'Platform overview dashboard', pri: 'P1', status: 'done',
          desc: 'At-a-glance KPIs and mix across all tenants.',
          ac: ['KPIs: agency count, seats in use, verticals live, MRR.', 'Agencies-by-vertical bar chart and plan mix.', 'Recent agencies table with status.'] },
        { id: 'SA-02', title: 'Agencies list', pri: 'P0', status: 'done',
          desc: 'Searchable, filterable, sortable list of every tenant in Table or Cards view with pagination.',
          ac: ['Filter by vertical, plan, status, seats; sort by name, seats, MRR; search by name/owner.', 'Paginates beyond page size.'] },
        { id: 'SA-03', title: 'Create agency', pri: 'P0', status: 'done',
          desc: 'Onboard a new tenant onto the platform.',
          ac: ['Capture name, owner, vertical, region, plan, status.', 'Seat limit follows plan; quota matrix auto-seeds from vertical.', 'New tenant appears in the list immediately.'] },
        { id: 'SA-04', title: 'Edit agency', pri: 'P1', status: 'done',
          desc: 'Change plan, vertical, region, owner or status of an existing tenant.',
          ac: ['Changing plan updates seat limit.', 'Changing status to active restores MRR; suspended/trial zero it.'] },
        { id: 'SA-05', title: 'Suspend / reactivate agency', pri: 'P1', status: 'done',
          desc: 'Quick status toggle from the row menu.',
          ac: ['Suspend sets status=suspended and MRR=0.', 'Reactivate restores plan MRR.', 'Confirmation toast shown.'] },
        { id: 'SA-06', title: 'Remove agency', pri: 'P2', status: 'done',
          desc: 'Delete a tenant and its data with a confirmation step.',
          ac: ['Destructive action requires explicit confirm modal.', 'Tenant disappears from list on confirm.'] },
        { id: 'SA-07', title: 'Verticals management', pri: 'P1', status: 'partial',
          desc: 'View and edit the verticals catalog — terminology and pricing categories.',
          ac: ['List every vertical with deal noun, unit, categories and agency count.', 'Edit terminology + categories in a modal.', 'PENDING: persist category edits and re-seed affected quotas.'] },
        { id: 'SA-08', title: 'Global discount guardrails', pri: 'P0', status: 'done',
          desc: 'Set the hard discount ceiling per vertical that no tenant quota may exceed.',
          ac: ['Slider 5–50% per vertical.', 'Saved guardrails clamp all tenant quota inputs for that vertical.'] },
        { id: 'SA-09', title: 'Plans & billing', pri: 'P2', status: 'partial',
          desc: 'Display plan tiers, seat limits, pricing and adoption.',
          ac: ['Show 4 plans with seats, price, feature list, agency count.', 'PENDING: editable plans and real billing integration.'] },
        { id: 'SA-10', title: 'Cross-tenant analytics', pri: 'P2', status: 'planned',
          desc: 'Usage, approval volume and discount trends across all tenants over time.',
          ac: ['Time-series of approvals, discount averages, active seats.', 'Filter by vertical and date range.'] }
      ]
    },
    {
      code: 'AG', name: 'Agency Admin', accent: 188,
      intro: 'The tenant operator. Sets quotas, manages salespeople and clears the approval queue for their agency.',
      tasks: [
        { id: 'AG-01', title: 'Agency overview dashboard', pri: 'P1', status: 'done',
          desc: 'Pending-approvals preview, KPIs and a live activity feed for the agency.',
          ac: ['KPIs: pending approvals, open deals + pipeline value, salespeople, decisions (30d).', '“Waiting on you” list links into the queue.', 'Activity feed shows recent requests + decisions.'] },
        { id: 'AG-02', title: 'Salespeople list', pri: 'P0', status: 'done',
          desc: 'Manage the agency’s sellers with their levels, in Table or Cards view.',
          ac: ['Search by name/email; filter by level; sort by name/level.', 'Per-level summary cards show self / cap ranges and headcount.'] },
        { id: 'AG-03', title: 'Change seller level', pri: 'P0', status: 'done',
          desc: 'Reassign a salesperson’s level, instantly changing their quota.',
          ac: ['Radio picker shows each level’s self/cap range.', 'Save updates level summaries and the seller row.'] },
        { id: 'AG-04', title: 'Add salesperson', pri: 'P1', status: 'planned',
          desc: 'Invite/create a new seller in the agency at a chosen level.',
          ac: ['Capture name, email, level.', 'New seller appears with zero deals and chosen level.'] },
        { id: 'AG-05', title: 'Agency settings', pri: 'P2', status: 'partial',
          desc: 'Agency profile, appearance and preferences.',
          ac: ['Reuses shared Settings (appearance, general).', 'PENDING: agency-specific fields (logo, default approver).'] }
      ]
    },
    {
      code: 'DQ', name: 'Discount Quotas', accent: 150,
      intro: 'How an Agency Admin defines what each seller level may discount per pricing category. The heart of the policy engine.',
      tasks: [
        { id: 'DQ-01', title: 'Quota matrix editor (Variation A)', pri: 'P0', status: 'done',
          desc: 'Editable level × category grid of self / cap percentages.',
          ac: ['Rows = levels, columns = categories; each cell has a self and a cap input.', 'Inputs clamp to guardrail; self/cap invariant enforced on edit.', 'Legend explains the three zones.'] },
        { id: 'DQ-02', title: 'Quota by-level cards (Variation B)', pri: 'P1', status: 'done',
          desc: 'Alternative layout: one card per level with stepper controls per category.',
          ac: ['Stepper +/- and direct entry for self and cap.', 'Edits the same underlying matrix as Variation A.'] },
        { id: 'DQ-03', title: 'Variation toggle', pri: 'P1', status: 'done',
          desc: 'Segmented control switches between Matrix and By-level layouts.',
          ac: ['Choice persists across reloads.', 'Both views always reflect the same saved values.'] },
        { id: 'DQ-04', title: 'Guardrail enforcement', pri: 'P0', status: 'done',
          desc: 'No quota input may exceed the platform guardrail for the tenant’s vertical.',
          ac: ['Values above the ceiling are clamped on entry.', 'Ceiling is shown in the page intro.'] },
        { id: 'DQ-05', title: 'Per-user quota override', pri: 'P2', status: 'planned',
          desc: 'Allow an Agency Admin to override a specific seller’s quota above their level default.',
          ac: ['Override is per seller, per category.', 'Falls back to level default when unset.', 'Clearly badged as an override in the UI.'] }
      ]
    },
    {
      code: 'AP', name: 'Approval Workflow', accent: 35,
      intro: 'The tiered routing and decisioning that fires whenever a discount exceeds a seller’s self-approve limit.',
      tasks: [
        { id: 'AP-01', title: 'Tiered routing rule', pri: 'P0', status: 'done',
          desc: 'Decide auto-approve / route-for-approval / block, and pick the approver tier by overage.',
          ac: ['≤ self → auto; self<x≤cap → pending; >cap → blocked.', 'Within the approval band, smaller overage routes to Team Lead; larger to Agency Admin.', 'Lead-level sellers always route to Agency Admin.'] },
        { id: 'AP-02', title: 'Approvals inbox', pri: 'P0', status: 'done',
          desc: 'Manager queue of pending requests with full context.',
          ac: ['Each card shows seller, level, deal, category, value, current→requested %, reason, routedTo, age.', 'A mini-meter shows where the request sits vs self/cap.', 'Pending and Decided tabs with counts.'] },
        { id: 'AP-03', title: 'Approve / reject with note', pri: 'P0', status: 'done',
          desc: 'Manager decides a request, optionally attaching a note.',
          ac: ['Approve and Reject actions per card.', 'Optional note is stored and shown on the decided card and to the seller.', 'Decision moves the card to Decided and updates counts.'] },
        { id: 'AP-04', title: 'Quote send-block on pending', pri: 'P1', status: 'planned',
          desc: 'A deal with a pending over-limit discount cannot be sent to the client until approved.',
          ac: ['Send action disabled while status=pending.', 'Approved unblocks send; rejected reverts to last valid discount.'] },
        { id: 'AP-05', title: 'Notifications', pri: 'P2', status: 'partial',
          desc: 'Surface approval events to the relevant people.',
          ac: ['In-app activity feed reflects requests + decisions.', 'PENDING: email / push notification to approver and requester.'] },
        { id: 'AP-06', title: 'Audit trail', pri: 'P1', status: 'partial',
          desc: 'Immutable record of who requested/decided what and when.',
          ac: ['Activity log captures actor, deal, %, timestamp for each event.', 'PENDING: tamper-evident export for compliance.'] },
        { id: 'AP-07', title: 'Auto-escalation on stale requests', pri: 'P2', status: 'planned',
          desc: 'Escalate a pending request to the next tier after an SLA window.',
          ac: ['Configurable SLA per tier.', 'Stale request re-routes upward and notifies.'] }
      ]
    },
    {
      code: 'SD', name: 'Sales — Apply Discount', accent: 265,
      intro: 'The salesperson’s standalone flow to apply a discount with a live quota check and one-step approval request.',
      tasks: [
        { id: 'SD-01', title: 'Deal picker + context', pri: 'P1', status: 'done',
          desc: 'Choose a deal and see its category, value and the seller’s level.',
          ac: ['Dropdown lists the seller’s deals.', 'Category, order value and level shown on selection.'] },
        { id: 'SD-02', title: 'Discount input + slider', pri: 'P0', status: 'done',
          desc: 'Set the discount via a number field and a synced slider.',
          ac: ['Number and slider stay in sync.', 'Net value and saving update live.', 'Value clamped to guardrail.'] },
        { id: 'SD-03', title: 'Live quota meter', pri: 'P0', status: 'done',
          desc: 'Three-zone meter visualising self / approval / blocked against the live discount.',
          ac: ['Green self zone, amber approval zone, red blocked zone.', 'Fill marker tracks the chosen discount.', 'self and cap labels positioned at their boundaries.'] },
        { id: 'SD-04', title: 'Outcome banner', pri: 'P0', status: 'done',
          desc: 'Plain-language verdict for the current discount.',
          ac: ['Within-limit (apply now), approval-needed (names approver), or blocked-above-cap.', 'Banner + primary action update together.'] },
        { id: 'SD-05', title: 'Apply within limit', pri: 'P1', status: 'done',
          desc: 'Apply a within-limit discount directly to the deal.',
          ac: ['Writes baseDiscount to the deal.', 'Confirmation toast.'] },
        { id: 'SD-06', title: 'Request-approval modal', pri: 'P0', status: 'done',
          desc: 'Capture a reason and submit an approval request routed to the correct tier.',
          ac: ['Shows routedTo, customer, current→requested %.', 'Reason is required.', 'Submitting creates a pending request visible to the Agency inbox + feed.'] },
        { id: 'SD-07', title: 'My requests panel', pri: 'P1', status: 'done',
          desc: 'Seller’s own request history with status and any approver note.',
          ac: ['Lists pending/approved/rejected with status pill.', 'Shows current→requested % and decision note.', 'Updates immediately after submitting.'] },
        { id: 'SD-08', title: 'Discount inside quote detail', pri: 'P1', status: 'planned',
          desc: 'Embed the same quota check + request action into the real quote/quote-detail screen.',
          ac: ['Discount field on the deal triggers the same routing.', 'Pending state blocks send (see AP-04).'] }
      ]
    },
    {
      code: 'CC', name: 'Cross-cutting & Platform UX', accent: 210,
      intro: 'Shared experience layers used by every persona.',
      tasks: [
        { id: 'CC-01', title: 'Persona launcher', pri: 'P1', status: 'done',
          desc: 'Entry screen to pick Site Admin, Agency Admin or Sales Person.',
          ac: ['Three cards describe each persona and link to its home.', 'Live platform stats shown.', 'Link back to the legacy airline workspace.'] },
        { id: 'CC-02', title: 'Persona-aware navigation', pri: 'P0', status: 'done',
          desc: 'Sidebar renders the right nav, brand tag and identity per persona.',
          ac: ['Nav config per persona; pending-approvals counter on the Approvals item.', 'Legacy sales pages keep their original identity.', '“Switch persona” returns to the launcher.'] },
        { id: 'CC-03', title: 'Shared list engine', pri: 'P1', status: 'done',
          desc: 'Reusable search + multi-filter + multi-sort + view-switch + pagination across lists.',
          ac: ['Search left; filter/sort/view right.', 'Per-screen default view; choice persists.', 'Pagination appears beyond page size.'] },
        { id: 'CC-04', title: 'Settings — Appearance', pri: 'P2', status: 'done',
          desc: 'Accent colour, corner style and light/dark theme in Settings, synced with Tweaks.',
          ac: ['Controls persist per browser and apply app-wide.'] },
        { id: 'CC-05', title: 'Domain-neutral terminology', pri: 'P1', status: 'partial',
          desc: 'Deal noun, money unit and categories come from the active vertical, not hard-coded airline labels.',
          ac: ['New persona screens read terminology from the vertical.', 'PENDING: generalise the legacy airline screens.'] },
        { id: 'CC-06', title: 'Tenant-scoped authentication', pri: 'P0', status: 'planned',
          desc: 'Real login that resolves the user’s persona + tenant instead of the launcher shortcut.',
          ac: ['Login routes user to their persona home.', 'Session scoped to tenant; platform admins exempt.'] },
        { id: 'CC-07', title: 'Accessibility & responsive pass', pri: 'P2', status: 'planned',
          desc: 'Keyboard, contrast and small-viewport review across new screens.',
          ac: ['All interactive controls keyboard-reachable.', 'Meets WCAG AA contrast.', 'Layouts hold at tablet widths.'] }
      ]
    }
  ]
};
